FROM node:20-alpine

ARG VITE_KEYCLOAK_ACCOUNT_URL

ENV VITE_KEYCLOAK_ACCOUNT_URL=$VITE_KEYCLOAK_ACCOUNT_URL

WORKDIR /app

COPY package.json .

RUN npm install

RUN npm i -g serve

COPY . .

RUN npm run build

EXPOSE 5173

CMD [ "serve", "-s", "dist", "-l", "5173" ]