services:
  
  caddy:
    container_name: caddy
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
    restart: unless-stopped
  
  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: on-failure
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: >
     redis-server /usr/local/etc/redis/redis.conf
     --requirepass ${REDIS_PASSWORD}
  
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_MULTIPLE_DBS=${POSTGRES_MULTIPLE_DBS}
    volumes:
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - postgres-data:/var/lib/postgresql/data`
  
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.3.0
    volumes:
      - ./keycloak:/opt/keycloak/data/import 
      - keycloak-data:/opt/keycloak/data
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=${KC_ADMIN_USERNAME}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=postgres
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_DB_SCHEMA=public
    command:
      - start-dev
      - --hostname=https://keycloak.local
      - --import-realm
      - --proxy-headers=xforwarded
      - --http-enabled=true
    restart: unless-stopped
    depends_on:
      - postgres

  backend:
    container_name: backend
    build: ./backend
    restart: unless-stopped
    ports:
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - redis
      - postgres
      - keycloak
  
  frontend:
    container_name: frontend
    build: ./frontend
    restart: unless-stopped
    ports:
      - "5173:5173" 
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    command: npm run dev -- --host

volumes:
  redis-data:
  caddy-data:
  keycloak-data:
  postgres-data:
  frontend-node-modules: